name: Test application

on:
  push:
    branches: ['main', 'develop']
  pull_request:
    branches: ['develop']

jobs:
  laravel-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: shivammathur/setup-php@15c43e89cdef867065b0213be354c2841860869e
        with:
          php-version: '8.1'
      - uses: actions/checkout@v3
      - name: Copy .env
        run: php -r "copy('.github/.env.pipeline', '.env');"
      - name: Create Database
        run: |
          mkdir -p database
          touch database/database.sqlite
      - name: Install Dependencies
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
      - name: Generate key
        run: php artisan key:generate
      - name: Install FrontEnd Dependencies
        run: npm i && npm run build
      - name: Directory Permissions
        run: chmod -R 777 storage bootstrap/cache
      - name: Make database migration
        run: |
          php artisan migrate
      - name: Scan whole codebase via PHPStan
        run: vendor/bin/phpstan analyse --no-progress
      - name: Execute tests (Unit and Feature tests) via PHPUnit
        run: vendor/bin/phpunit --no-interaction
